apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: testing123-asdfase
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.config.host }}
spec:
  hosts:
    - {{ .Values.config.host }}
  gateways:
    - istio-system/public-gateway
  http:
    - match:
        - port: 443
      route:
        - destination:
            port:
              number: 8080
            host: testing123-asdfase-{{ .Values.config.servingSlot }}
